//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTry1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string prodname { get; set; }
        public int cat_id { get; set; }
        public int brand_id { get; set; }
        public int qty { get; set; }
        public decimal price { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
    }
}
